development:
  adapter: postgresql
  encoding: unicode
  database: starter_package_development
  host: localhost
  pool: 5
  username: postgres
  password: root
  min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: starter_package_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: starter_package_production
  pool: 5
  username: postgres
  password: root

staging:
  adapter: postgresql
  encoding: unicode
  database: starter_package_staging
  pool: 5
  username: postgres
  password: root
